#!/bin/sh
# 
# Copyright (C) 2013 - Eric Shubert <eric@datamatters.us>
# Secure mysql and install vpopmail database for QMailToaster
########################################################################
# Change Log
# 12/05/13 shubes - created
########################################################################

mysql_root_pw="QMailToasterRootPassword"
vpopmail_local_pw="SsEeCcRrEeTt"

mysql_secure_installation "" "$mysql_root_pw"

if [ $? -ne 0 ]; then
  echo "$me - unsuccessful mysql_secure_installation - terminating"
  exit 1
fi

# Create vpopmail database

mysqladmin create vpopmail -uroot -p$mysql_root_pw
mysqladmin -uroot -p$mysql_root_pw reload
mysqladmin -uroot -p$mysql_root_pw refresh

# Grant access to the vpopmail user on from localhost
echo "GRANT ALL PRIVILEGES ON vpopmail.* \
      TO vpopmail@localhost IDENTIFIED BY 'SsEeCcRrEeTt'" \
      | mysql -uroot -p$mysql_root_pw
mysqladmin -uroot -p$mysql_root_pw reload
mysqladmin -uroot -p$mysql_root_pw refresh

